# Site settings
title: Bhameyie
description: A Pragmatic Software Engineer
email: muzzled.coder@gmail.com
baseurl: ""
url: "http://47ron.in"
base: http://47ron.in
twitter_username: bhameyie
github_username: bhameyie
paginate: 3

destination: ./_site

# Build settings
markdown: kramdown
highlighter: pygments
permalink:     /blog/:year/:month/:day/:title.html
paginate_path: /page:num
gems:
  - jekyll-gist
  - jekyll-paginate
events:
  - image: /assets/images/timeline/spidertocat.png
    date: "September 2011 - Today"
    description: "Working in the financial industry"
  - image: /assets/images/timeline/baracktocat.jpg
    date: "June 2011"
    description: "Graduated with a Bachelor and a Master of Science in Software Engineering"

# First image of the Timeline

timeline-img: https://avatars0.githubusercontent.com/u/1227030?v=3&s=460
