# Site settings
title: 47 Ronin
email: muzzled.coder@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  From Journeyman To Zen Master
baseurl: ""
url: "http://47ron.in" # the base hostname & protocol for your site
twitter_username: bhameyie
github_username: bhameyie

paginate: 6

destination: ./_site

# Build settings
markdown: kramdown

permalink:     /blog/:year/:month/:day/:title.html
paginate_path: /page:num
