# Site settings
title: Your awesome title
email: bhameyie@47ron.in
description: > # this means to ignore newlines until "baseurl:"
  A blog about Distributed Systems, the Cloud, Mobile Developement and that Developer life.
baseurl: ""
url: "http://www.47ron.in" # the base hostname & protocol for your site
twitter_username: bhameyie
github_username: bhameyie

paginate: 5

destination: ./_site

# Build settings
markdown: kramdown

permalink:     /blog/:year/:month/:day/:title.html
paginate_path: /page:num