# Site settings
title: 47 Ronin
email: muzzled.coder@gmail.com
baseurl: ""
url: "http://47ron.in" # the base hostname & protocol for your site
twitter_username: bhameyie
github_username: bhameyie

paginate: 3

destination: ./_site

# Build settings
markdown: kramdown

permalink:     /blog/:year/:month/:day/:title.html
paginate_path: /page:num
