- name: Strategy
  icon: icon-Chess
  content: >
    Helping businesses iron out plans that maximizes their revenues. <br/>
    Helping teams establish attainable technical visions and process structures that lead to maintainable software and scalable teams.

- name: Architecture
  icon: icon-Transform-2
  content: >
    Design and architect maintainable and scalable systems of varying complexities.

- name: Developement
  icon: icon-Monitor-Tablet
  content: >
    Develop, maintain and test software. Areas of expertise includes API Developement, Web Developement and Mobile Developement.

- name: Devops
  icon: icon-Leafs-2
  content: >
    Build tooling and establish platforms to support Development efforts, maintain assets deployed on-site or in the cloud (AWS, Digital Ocean).
